name: change in _annotations
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - annotations/**
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: sudo gem install jekyll
      - run: jekyll build
      - run: python3 -c "exec(\"import glob, json, os/\n/\nif len(glob.glob(\'_annotations\')) == 0:/\n\tos.mkdir(\'_annotations\')/\nfor file in glob.glob(\'annotations/*\'):/\n\tif \'.json\' in file and \'collection.json\' not in file:/\n\t\tjsoncontents = json.load(open(file, \'rb\'))/\n\t\tannolist = jsoncontents[\'resources\'] if \'resources\' in jsoncontents.keys() else jsoncontents[\'items\']/\n\t\tcanvas = annolist[0][\'on\'][0][\'full\']/\n\t\tfilename = os.path.basename(file).replace(\'.json\', \'\') + \'-list.json\'/\n\t\twith open(\'_annotations/{}\'.format(filename), \'w\') as f:/\n\t\t\tcontext = jsoncontents[\'@context\']/\n\t\t\tif \'3\' in context:/\n\t\t\t\tannotype = "AnnotationPage"/\n\t\t\t\titemskey = "items"/\n\t\t\telse:/\n\t\t\t\tannotype = "oa:AnnotationList"/\n\t\t\t\titemskey = "resources"/\n\t\t\ttext = \'---/\ncanvas_id: "\' + canvas + \'"/\n---/\n{% assign annotations = site.annotations | where: "canvas", page.canvas_id | sort: "order" | map: "content" %}/\n{/\n"@context": "\' + context + \'",/\n"id": "{{ site.url }}{{ site.baseurl }}{{page.url}}",/\n"type": "\' + annotype + \'",/\n"%s": [{{ annotations | join: ","}}] }\'%(itemskey)/\n\t\t\tf.write(text)/\n\t\tfor order, item in enumerate(annolist):/\n\t\t\tidfield = \'id\' if \'id\' in item.keys() else \'@id\'/\n\t\t\tfilename = item[idfield].split(\'/\')[-1]/\n\t\t\twith open(\'_annotations/{}\'.format(filename), \'w\') as f:/\n\t\t\t\ttext = \'---/\ncanvas: "{}"/\norder: {}/\n---/\n{}\'.format(canvas, order, json.dumps(item,indent=4))/\n\t\t\t\tf.write(text)\")"
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase false
          git add -A
          git commit -m "convert annotations to _annotations" -a || echo "No changes to commit"
      - name: pull
        run: git pull origin main
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
    
